# Generated by Django 4.2 on 2025-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Moluscs', 'Moluscs'), ('Eggs', 'Eggs'), ('Fish', 'Fish'), ('Lupin', 'Lupin'), ('Soya', 'Soya'), ('Milk', 'Milk'), ('Peanuts', 'Peanuts'), ('Gluten', 'Gluten'), ('Crustaceans', 'Crustaceans'), ('Mustard', 'Mustard'), ('Nuts', 'Nuts'), ('Sesame', 'Sesame'), ('Celery', 'Celery'), ('Sulphite', 'Sulphite'), ('Eggplant', 'Eggplant'), ('Carrots', 'Carrots'), ('Peas', 'Peas'), ('Tomatoes', 'Tomatoes'), ('Coriander', 'Coriander'), ('Citrus', 'Citrus'), ('Berries', 'Berries'), ('Bananas', 'Bananas'), ('Garlic', 'Garlic'), ('Onions', 'Onions')], max_length=100, unique=True, verbose_name='Name')),
                ('addDifAllergies', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Add different allergy')),
            ],
        ),
    ]
