# Generated by Django 4.2 on 2025-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='daily_protein_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
