# Generated by Django 4.2 on 2025-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_daily_protein_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='daily_protein_goal',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
