# Generated by Django 4.2 on 2025-05-29 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='fridge',
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fridge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
    ]
