# Generated by Django 4.2 on 2025-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('calories', models.FloatField(verbose_name='Calories')),
                ('fat', models.FloatField(verbose_name='Fat')),
                ('glucose', models.FloatField(verbose_name='Glucose')),
                ('measurement', models.CharField(choices=[('g/100', 'per 100 grams'), ('ml/100', 'per 100 milliliters')], default='g/100', max_length=10, verbose_name='Measurement')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
    ]
