# Generated by Django 4.2 on 2025-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='glucose',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(default=0.0, verbose_name='Carbohydrates'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.FloatField(default=0.0, verbose_name='Fiber'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='protein',
            field=models.FloatField(default=0.0, verbose_name='Protein'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='salt',
            field=models.FloatField(default=0.0, verbose_name='Salt'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='saturated_fat',
            field=models.FloatField(default=0.0, verbose_name='Saturated Fat'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(default=0.0, verbose_name='Sugar'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.IntegerField(default=0.0, verbose_name='Fat'),
        ),
    ]
